# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29dcebe9d99509a0c9758566f146629619bf0ee32d0dfbd0194924b186c9d48b2f2a10d488039d8e695d71fa8314f6b45ce9e60d778c537935b557e18c1d045

test:
  secret_key_base: dc0506b93d16155d1404860400e96a22316a8883058ade00d6282cf3b4f3edd1caf19ec4fd1ee27d057ae9dd3c84cdc9d82a5e8119211f8fc6aac0fde11ae084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 4fc145c5ee2116b204e51814c6b02915e0050b443254b7da3397e276ef5482eabfa9a614370cd34f7c1f3cfb0c3db2d2d53d1dcafb20c5d200558e5c21a0a02d
  #secret_token
